language: cpp
before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install gcc-8 g++-8 -y
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake . -DBUILD_TESTS=ON  -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++-8
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T GetDataByURL-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uruknez:$BINTRAY_API_KEY "https://api.bintray.com/content/ruknez/MailTestTask/Get/$TRAVIS_BUILD_NUMBER/GetDataByURL-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

